name: ci-python

on: 
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      # Step 1: obtain repo from GitHub
      - uses: actions/checkout@v2

      # Install dependencies
      - name: install deps
        run: sudo apt install nodejs

      # Step 3: run program
      - name: run program
        run: node factorial.js 